[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"

[font]
builtin_box_drawing = true
size = 11.0

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 100000
multiplier = 3

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.9
resize_increments = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 160
lines = 50
